# Generated by Django 3.0.6 on 2020-05-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('thumbnail', models.CharField(max_length=255, verbose_name='サムネイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Channel')),
            ],
            options={
                'verbose_name': '動画',
                'verbose_name_plural': '動画',
            },
        ),
    ]
