# Generated by Django 3.0.6 on 2020-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True, verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='タイトル'),
        ),
    ]
