# Generated by Django 3.0.6 on 2020-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='end_at',
            field=models.IntegerField(null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='song',
            name='start_at',
            field=models.IntegerField(null=True, verbose_name='開始時間'),
        ),
    ]
