# Generated by Django 3.0.6 on 2020-09-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20200520_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_member_only',
            field=models.BooleanField(default=False, verbose_name='メンバー限定'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='公開フラグ'),
        ),
    ]
