# Generated by Django 3.2.10 on 2021-12-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20211228_1449'),
    ]

    operations = [
        migrations.DeleteModel('Video'),
        migrations.RenameModel('Newvideo', 'Video'),
    ]
