# Generated by Django 3.2.10 on 2022-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_rename_newvideo_song_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='オリジナル'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_stream',
            field=models.BooleanField(default=True, verbose_name='歌配信'),
        ),
    ]
